
spring:
  application:
    name: quote-service
  cloud:
    config:
      uri: http://localhost:8088


# Server config
#server:
#  port: ${PORT:7878}

# Spring config



#  logging:
#    level:
#      org.springframework: WARN
#      org.hibernate: WARN


#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost

